### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by mderler** [MichaelGloessl04/PiRechner_02_12#1]
I`ve been searching for a pi calculator for about 4 months now till I came across this repo.

I cloned your repository an ran the code on my good ol` HP pc. But it seems there is some sort of bug.
If you could help me out or work on this bug it would really help me out man.

I will be enrolling in uni next semester and really need a way to calculate pi. You know really **crunch** those **numbers**. Bro I am really close to **calculate** the area of a circle, you know what I mean.

So please man, if you could fix the code it would really benefit everyone.

Keep up the good work man.
Cheers

**Comment by MichaelGloessl04** [comment]
Hi @mderler ,
On my machine everything seems to work correctly 🤔 mabey if you could send some screenshots so i could recreate this bug?
- Regards Micheal from 4AHIT

**Comment by mderler** [comment]
![image](https://github.com/MichaelGloessl04/PiRechner_02_12/assets/55692268/7a01735f-9d5a-44b9-8a03-139baa41e7f6)

@MichaelGloessl04 Here a screenshot

Hope that helpes ;)

**Comment by mderler** [comment]
Hi again

I worked that error out
If u could accept pull request it would be good

Pull Reuqest: #2
